import { School, SchoolType } from "./types";

export const schoolList: School[] = 
[{
   "name": "对外经贸－法国巴黎第一大学",
   "majorName": "企业管理硕士",
   "location": "北京",
   "fee": "18.96万",
   "type": SchoolType.PART_TIME
}, {
   "name": "对外经贸－美国西雅图城市大学",
   "majorName": "MBA",
   "location": "北京",
   "fee": "17.96万",
   "type": SchoolType.PART_TIME
}, {
   "name": "北京邮电大学－法国里昂商学院",
   "majorName": "EMBA",
   "location": "北京",
   "fee": "42.8万",
   "type": SchoolType.PART_TIME
}, {
   "name": "对外经贸－法国诺欧商学院",
   "majorName": "零售业管理硕士",
   "location": "北京",
   "fee": "17.95万",
   "type": SchoolType.PART_TIME
}, {
   "name": "中国人民大学－加拿大女王大学",
   "majorName": "金融学硕士",
   "location": "北京",
   "fee": "36.8万",
   "type": SchoolType.PART_TIME
}, {
   "name": "社科院－美国杜兰大学",
   "majorName": "能源管理硕士",
   "location": "北京",
   "fee": "25.8万",
   "type": SchoolType.PART_TIME
}, {
   "name": "社科院－美国杜兰大学",
   "majorName": "金融管理硕士",
   "location": "",
   "fee": "32.8万",
   "type": SchoolType.PART_TIME
}, {
   "name": "中国矿业大学－加拿大魁北克大学",
   "majorName": "MBA",
   "location": "北京",
   "fee": "24万",
   "type": SchoolType.PART_TIME
}, {
   "name": "北京科技大学－美国阿灵顿商学院",
   "majorName": "EMBA",
   "location": "北京",
   "fee": "30.8万",
   "type": SchoolType.PART_TIME
}, {
   "name": "中国传媒大学国际传媒教育学院",
   "majorName": "传媒学 新闻与传播 传媒经济学",
   "location": "北京",
   "fee": "16万",
   "type": SchoolType.PART_TIME
}, {
   "name": "北京城市学院-英国华威大学",
   "majorName": "项目管理",
   "location": "北京、上海",
   "fee": "18.8万",
   "type": SchoolType.PART_TIME
}, {
   "name": "北京国家会计学院－香港城市大学",
   "majorName": "智能会计与金融科技应用理学硕士",
   "location": "北京",
   "fee": "25万",
   "type": SchoolType.PART_TIME
}, {
   "name": "江西财经－美国纽约理工",
   "majorName": "MBA",
   "location": "北京、上海、深圳",
   "fee": "16.3万",
   "type": SchoolType.PART_TIME
}, {
   "name": "中央财经大学－美国史蒂文斯理工学院",
   "majorName": "项目管理理学硕士",
   "location": "北京",
   "fee": "21.8万",
   "type": SchoolType.PART_TIME
}, {
   "name": "北京理工大学－德国德累斯顿工业大学",
   "majorName": "职业教育和人力资源开发",
   "location": "北京",
   "fee": "15.8万",
   "type": SchoolType.PART_TIME
}, {
   "name": "首都师范大学－澳大利亚弗林德斯大学",
   "majorName": "教育硕士",
   "location": "北京",
   "fee": "9.6万",
   "type": SchoolType.PART_TIME
}, {
   "name": "清华大学－香港中文大学",
   "majorName": "金融MBA",
   "location": "北京",
   "fee": "43.8万",
   "type": SchoolType.PART_TIME
}, {
   "name": "天津财经大学－加拿大西三一大学",
   "majorName": "国际MBA",
   "location": "北京",
   "fee": "18万",
   "type": SchoolType.PART_TIME
}, {
   "name": "北京大学－伦敦大学学院",
   "majorName": "MBA",
   "location": "北京",
   "fee": "36.8万",
   "type": SchoolType.PART_TIME
}, {
   "name": "北京大学－弗拉瑞克商学院",
   "majorName": "MBA",
   "location": "北京",
   "fee": "36.8万",
   "type": SchoolType.PART_TIME
}, {
   "name": "上海交通大学-南洋理工大学",
   "majorName": "EMBA",
   "location": "上海",
   "fee": "68万",
   "type": SchoolType.PART_TIME
}, {
   "name": "同济大学-德克萨斯大学",
   "majorName": "EMBA",
   "location": "上海",
   "fee": "40万",
   "type": SchoolType.PART_TIME
}, {
   "name": "北京邮电大学-法国里昂商学院",
   "majorName": "EMBA",
   "location": "上海",
   "fee": "42.8万",
   "type": SchoolType.PART_TIME
}, {
   "name": "上海交通大学-法国凯致商学院",
   "majorName": "MBA",
   "location": "上海",
   "fee": "41.8万",
   "type": SchoolType.PART_TIME
}, {
   "name": "上海交通大学-加拿大不列颠哥伦比亚大学",
   "majorName": "MBA",
   "location": "上海",
   "fee": "36.2万",
   "type": SchoolType.PART_TIME
}, {
   "name": "东华大学-加拿大卡尔顿大学",
   "majorName": "MBA",
   "location": "上海",
   "fee": "18万",
   "type": SchoolType.PART_TIME
}, {
   "name": "上海国家会计学院-美国亚利桑那州立大学",
   "majorName": "EMBA",
   "location": "上海",
   "fee": "48.6万",
   "type": SchoolType.PART_TIME
}, {
   "name": "北京城市学院-英国华威大学",
   "majorName": "项目管理",
   "location": "北京、上海",
   "fee": "18.8万",
   "type": SchoolType.PART_TIME
}, {
   "name": "天津财经大学－加拿大西三一大学",
   "majorName": "国际MBA",
   "location": "上海",
   "fee": "18.8万",
   "type": SchoolType.PART_TIME
}, {
   "name": "上海财经大学-美国韦伯斯特大学",
   "majorName": "MBA",
   "location": "上海",
   "fee": "29.8万",
   "type": SchoolType.PART_TIME
}, {
   "name": "南昌大学－普瓦提埃大学",
   "majorName": "国际企业管理硕士",
   "location": "上海",
   "fee": "19.8万",
   "type": SchoolType.PART_TIME
}, {
   "name": "上海大学－悉尼科技大学",
   "majorName": "工程管理硕士",
   "location": "上海",
   "fee": "15.8万",
   "type": SchoolType.PART_TIME
}, {
   "name": "上海大学－悉尼科技大学",
   "majorName": "金融硕士",
   "location": "上海",
   "fee": "18.8万",
   "type": SchoolType.PART_TIME
}, {
   "name": "复旦大学－香港大学",
   "majorName": "国际MBA",
   "location": "上海",
   "fee": "49.8万",
   "type": SchoolType.PART_TIME
}, {
   "name": "上海国家会计学院－香港中文大学",
   "majorName": "高级财务专业硕士",
   "location": "上海",
   "fee": "30.8万",
   "type": SchoolType.PART_TIME
}, {
   "name": "西安交通大学－法国SKEMA商学院",
   "majorName": "创业与创新管理 人工智能大数据",
   "location": "上海",
   "fee": "23万",
   "type": SchoolType.PART_TIME
}, {
   "name": "西安交通大学－加拿大阿尔伯塔大学",
   "majorName": "金融财务管理硕士",
   "location": "上海",
   "fee": "27.16万",
   "type": SchoolType.PART_TIME
}, {
   "name": "华东理工大学－澳大利亚堪培拉大学",
   "majorName": "MBA",
   "location": "上海",
   "fee": "25.8万",
   "type": SchoolType.PART_TIME
}, {
   "name": "南开大学－澳大利亚弗林德斯大学",
   "majorName": "国际经贸关系 教育领导与管理 医院管理",
   "location": "天津",
   "fee": "14万",
   "type": SchoolType.PART_TIME
}, {
   "name": "天津师范大学与韩国世翰大学",
   "majorName": "情报学 教育行政学",
   "location": "天津",
   "fee": "8.6万+4500美金",
   "type": SchoolType.PART_TIME
}, {
   "name": "天津商业大学与美国东密西根大学",
   "majorName": "人力资源管理硕士",
   "location": "天津",
   "fee": "9.6万",
   "type": SchoolType.PART_TIME
}, {
   "name": "天津财经大学－加拿大西三一大学",
   "majorName": "国际MBA",
   "location": "天津",
   "fee": "16万",
   "type": SchoolType.PART_TIME
}, {
   "name": "沈阳工业大学－美国班尼迪克大学",
   "majorName": "企业管理硕士",
   "location": "沈阳",
   "fee": "8万",
   "type": SchoolType.PART_TIME
}, {
   "name": "沈阳建筑大学－美国班尼迪克大学",
   "majorName": "信息管理硕士",
   "location": "沈阳",
   "fee": "10万",
   "type": SchoolType.PART_TIME
}, {
   "name": "大连医科大学与美国班尼迪克大学",
   "majorName": "公共卫生硕士",
   "location": "大连",
   "fee": "9万",
   "type": SchoolType.PART_TIME
}, {
   "name": "浙江工商大学－魁北克大学",
   "majorName": "项目管理硕士",
   "location": "杭州",
   "fee": "15万",
   "type": SchoolType.PART_TIME
}, {
   "name": "浙江师范大学-澳大利亚伊迪斯科文大学",
   "majorName": "教育管理硕士",
   "location": "杭州",
   "fee": "7.85万",
   "type": SchoolType.PART_TIME
}, {
   "name": "浙江大学-香港理工大学",
   "majorName": "品质管理",
   "location": "杭州",
   "fee": "21.6万",
   "type": SchoolType.PART_TIME
}, {
   "name": "浙江大学-香港理工大学",
   "majorName": "旅游管理",
   "location": "杭州",
   "fee": "25.2万",
   "type": SchoolType.PART_TIME
}, {
   "name": "浙江大学-香港理工大学",
   "majorName": "房地产",
   "location": "杭州",
   "fee": "16.6万",
   "type": SchoolType.PART_TIME
}, {
   "name": "云南财经大学－英国格林威治大学",
   "majorName": "项目管理",
   "location": "昆明",
   "fee": "15.9万",
   "type": SchoolType.PART_TIME
}, {
   "name": "云南财经大学－英国格林威治大学",
   "majorName": "房地产",
   "location": "昆明",
   "fee": "15.4万",
   "type": SchoolType.PART_TIME
}, {
   "name": "电子科技大学－美国韦伯斯特大学",
   "majorName": "MBA",
   "location": "成都",
   "fee": "15.8万",
   "type": SchoolType.PART_TIME
}, {
   "name": "贵州大学－魁北克大学",
   "majorName": "项目管理硕士",
   "location": "贵州",
   "fee": "7万",
   "type": SchoolType.PART_TIME
}, {
   "name": "西安交通大学-美国阿灵顿商学院",
   "majorName": "EMBA",
   "location": "西安",
   "fee": "30万",
   "type": SchoolType.PART_TIME
}, {
   "name": "烟台大学－德国特里尔大学",
   "majorName": "国际物质流管理理学硕士",
   "location": "烟台",
   "fee": "12万",
   "type": SchoolType.PART_TIME
},{
   "name": "清华大学－香港中文大学",
   "majorName": "金融MBA",
   "location": "深圳",
   "fee": "43.8万",
   "type": SchoolType.PART_TIME
}, {
   "name": "西安交通大学－加拿大阿尔伯塔大学",
   "majorName": "金融财务管理硕士",
   "location": "深圳",
   "fee": "26.96万",
   "type": SchoolType.PART_TIME
}, {
   "name": "中山大学-美国明尼苏达大学",
   "majorName": "EMBA",
   "location": "广州",
   "fee": "51.8万",
   "type": SchoolType.PART_TIME
}, {
   "name": "广东外语外贸大学-英国雷丁大学",
   "majorName": "英语教育",
   "location": "广州",
   "fee": "10万",
   "type": SchoolType.PART_TIME
}, {
   "name": "广东外语外贸大学-英国利兹大学",
   "majorName": "英语教育",
   "location": "广州",
   "fee": "14万",
   "type": SchoolType.PART_TIME
}, {
   "name": "江西财经－美国纽约理工",
   "majorName": "MBA",
   "location": "北京、上海、深圳",
   "fee": "16.3万",
   "type": SchoolType.PART_TIME
},{
    "location": "北京",
    "name": "中国传媒大学与英国威斯敏斯特大学的国际媒体商务硕士项目",
    "type": SchoolType.FULL_TIME,
    "majorName": "国际媒体商务",
    "lengthOfSchooling": "2年",
    "fee": " 17.5万人民币"
}, {
    "location": "北京",
    "name": "中国传媒大学国际传媒教育学院（中国传媒大学诺丁汉特伦特大学）",
    "type": SchoolType.FULL_TIME,
    "majorName": "传播学(媒介与全球化)",
    "lengthOfSchooling": "2年",
    "fee": "16万人民币"
}, {
    "location": "北京",
    "name": "中国传媒大学国际传媒教育学院（中国传媒大学诺丁汉特伦特大学）",
    "type": SchoolType.FULL_TIME,
    "majorName": "新闻与传播(国际广播电视)",
    "lengthOfSchooling": "2年",
    "fee": "16万人民币"
}, {
    "location": "北京",
    "name": "中国传媒大学国际传媒教育学院（中国传媒大学诺丁汉特伦特大学）",
    "type": SchoolType.FULL_TIME,
    "majorName": "传媒经济学(文博管理)",
    "lengthOfSchooling": "2年",
    "fee": "16万人民币"
}, {
    "location": "浙江",
    "name": "浙江工业大学与英国利兹贝克特大学合作举办国际贸易与金融硕士学位教育",
    "type": SchoolType.FULL_TIME,
    "majorName": "国际贸易与金融硕士",
    "lengthOfSchooling": "1年",
    "fee": "96000人民币\n"
}, {
    "location": "烟台",
    "name": "烟台大学-德国特里尔应用技术大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "国际物流管理理学硕士",
    "lengthOfSchooling": "两年制",
    "fee": "13.6万"
}, {
    "location": "广州",
    "name": "广东外语外贸大学-英国雷丁大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "英语教育硕士",
    "lengthOfSchooling": "一年制",
    "fee": "10500镑"
}, {
    "location": "深圳",
    "name": "深圳大学-法国南特高等学院",
    "type": SchoolType.FULL_TIME,
    "majorName": "金融科技与风险控制",
    "lengthOfSchooling": "两年制",
    "fee": "15万"
}, {
    "location": "杭州",
    "name": "浙江工商大学-萨塞克斯大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "机器人与自动化系统",
    "lengthOfSchooling": "1.5年",
    "fee": "15万元"
}, {
    "location": "杭州",
    "name": "浙江工商大学-萨塞克斯大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "人工智能与自适应系统",
    "lengthOfSchooling": "1.5年",
    "fee": "15万"
}, {
    "location": "深圳",
    "name": "天津大学-美国佐治亚理工学院",
    "type": SchoolType.FULL_TIME,
    "majorName": "电子与计算机工程(ECE) 硕士",
    "lengthOfSchooling": "1.5-2年",
    "fee": "4.5万元/生/学期"
}, {
    "location": "深圳",
    "name": "北京师范大学-香港浸会大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "传媒管理",
    "lengthOfSchooling": "一年制",
    "fee": "150,000元"
}, {
    "location": "深圳",
    "name": "北京师范大学-香港浸会大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "影视与新媒体制片管理",
    "lengthOfSchooling": "一年制",
    "fee": "150,000元"
}, {
    "location": "深圳",
    "name": "北京师范大学-香港浸会大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "传理学",
    "lengthOfSchooling": "一年制",
    "fee": "150,000元"
}, {
    "location": "深圳",
    "name": "北京师范大学-香港浸会大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "人工智能与数码媒体",
    "lengthOfSchooling": "一年制",
    "fee": "150,000元"
}, {
    "location": "深圳",
    "name": "北京师范大学-香港浸会大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "互动媒体",
    "lengthOfSchooling": "一年制",
    "fee": "150,000元"
}, {
    "location": "深圳",
    "name": "北京师范大学-香港浸会大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "社会工作",
    "lengthOfSchooling": "一年制",
    "fee": "140,000港币"
}, {
    "location": "北京",
    "name": "北京语言大学&法国克莱蒙高等商学院",
    "type": SchoolType.FULL_TIME,
    "majorName": "商业智能与分析",
    "lengthOfSchooling": "1.5年",
    "fee": "14.8万"
}, {
    "location": "北京",
    "name": "北京城市学院&英国华威大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "项目管理",
    "lengthOfSchooling": "1.5",
    "fee": "18万元人民币"
}, {
    "location": "上海",
    "name": "上海海事大学&瑞典世界海事大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "国际运输与物流",
    "lengthOfSchooling": "2年",
    "fee": "93000元"
}, {
    "location": "武汉",
    "name": "中南财经政法大学&意大利罗马第一大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "欧洲学：比较法与欧洲法",
    "lengthOfSchooling": "2年",
    "fee": "RMB 7.5万元/学年"
}, {
    "location": "江苏",
    "name": "江苏师范大学&俄罗斯普列汉诺夫经济大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "国际贸易学",
    "lengthOfSchooling": "2年",
    "fee": "66266元人民币"
}, {
    "location": "江苏",
    "name": "南京师范大学&美国马里兰大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "刑事司法学",
    "lengthOfSchooling": "2年",
    "fee": "133467人民币\n"
}, {
    "location": "大连",
    "name": "大连海事大学&瑞典世界海事大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "海上安全与环境管理",
    "lengthOfSchooling": "14个月",
    "fee": "89900元"
}, {
    "location": "海南",
    "name": "海南医学院西英格兰学院",
    "type": SchoolType.FULL_TIME,
    "majorName": "国际护理实践",
    "lengthOfSchooling": "1.5年",
    "fee": "98000人民币/年"
}, {
    "location": "海南",
    "name": "海南医学院西英格兰学院",
    "type": SchoolType.FULL_TIME,
    "majorName": "公共卫生",
    "lengthOfSchooling": "1.5年",
    "fee": "98000人民币/年"
}, {
    "location": "海南",
    "name": "海南医学院西英格兰学院",
    "type": SchoolType.FULL_TIME,
    "majorName": "康复",
    "lengthOfSchooling": "1.5年",
    "fee": "98000人民币/年"
},{
    "location": "上海",
    "name": "上海纽约大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "数据分析和商业计算",
    "lengthOfSchooling": "1年",
    "fee": "71016美元"
}, {
    "location": "上海",
    "name": "上海纽约大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "计量金融",
    "lengthOfSchooling": "1年\n",
    "fee": "71016美元"
}, {
    "location": "上海",
    "name": "上海纽约大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "营销与零售科学",
    "lengthOfSchooling": "1年",
    "fee": "71016美元"
}, {
    "location": "上海",
    "name": "上海纽约大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "组织管理与战略",
    "lengthOfSchooling": "1年",
    "fee": "71016美元"
}, {
    "location": "上海",
    "name": "上海纽约大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "互动媒体艺术",
    "lengthOfSchooling": "1年",
    "fee": "71016美元"
}, {
    "location": "上海",
    "name": "上海纽约大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "社会工作",
    "lengthOfSchooling": "2年",
    "fee": "71016美元"
}, {
    "location": "上海",
    "name": "上海纽约大学",
    "type": SchoolType.PART_TIME,
    "majorName": "英语教育",
    "lengthOfSchooling": "2年",
    "fee": "71016美元"
}, {
    "location": "江苏",
    "name": "昆山杜克大学",
    "type": SchoolType.PART_TIME,
    "majorName": "电子与计算机工程",
    "lengthOfSchooling": "2年",
    "fee": "799779元"
}, {
    "location": "江苏",
    "name": "昆山杜克大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "环境政策",
    "lengthOfSchooling": "2年",
    "fee": "36万元"
}, {
    "location": "江苏",
    "name": "昆山杜克大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "管理学",
    "lengthOfSchooling": "2年",
    "fee": "200000人民币"
}, {
    "location": "江苏",
    "name": "昆山杜克大学",
    "type": [SchoolType.FULL_TIME, SchoolType.PART_TIME],
    "majorName": "全球健康理学",
    "lengthOfSchooling": "全日制2年/非全日制4年",
    "fee": "370000人民币"
}, {
    "location": "江苏",
    "name": "昆山杜克大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "医学物理学",
    "lengthOfSchooling": "2年",
    "fee": "36万元"
}, {
    "location": "江苏",
    "name": "西交利物浦大学",
    "type": [SchoolType.FULL_TIME, SchoolType.PART_TIME],
    "majorName": "管理学",
    "lengthOfSchooling": "全日制18个月/非全日制30个月",
    "fee": "180000元"
}, {
    "location": "江苏",
    "name": "西交利物浦大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "高级化学",
    "lengthOfSchooling": "全日制24个月",
    "fee": "180000元"
}, {
    "location": "江苏",
    "name": "西交利物浦大学",
    "type": [SchoolType.FULL_TIME, SchoolType.PART_TIME],
    "majorName": "建筑工程管理",
    "lengthOfSchooling": "全日制18个月/非全日制36个月",
    "fee": "135000元"
}, {
    "location": "江苏",
    "name": "西交利物浦大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "建筑设计",
    "lengthOfSchooling": "全日制24个月",
    "fee": "200000元"
}, {
    "location": "江苏",
    "name": "西交利物浦大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "经济与金融",
    "lengthOfSchooling": "全日制18个月",
    "fee": "180000元"
}, {
    "location": "江苏",
    "name": "西交利物浦大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "计算机科学",
    "lengthOfSchooling": "全日制18个月",
    "fee": "180000元"
}, {
    "location": "江苏",
    "name": "西交利物浦大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "金融学",
    "lengthOfSchooling": "全日制18个月",
    "fee": "180000元"
}, {
    "location": "江苏",
    "name": "西交利物浦大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "金融数学",
    "lengthOfSchooling": "全日制18个月",
    "fee": "180000元"
}, {
    "location": "江苏",
    "name": "西交利物浦大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "金融计算学",
    "lengthOfSchooling": "全日制18个月",
    "fee": "180000元"
}, {
    "location": "江苏",
    "name": "西交利物浦大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "精算学",
    "lengthOfSchooling": "全日制18个月",
    "fee": "150000元"
}, {
    "location": "江苏",
    "name": "西交利物浦大学",
    "type": [SchoolType.FULL_TIME, SchoolType.PART_TIME],
    "majorName": "可持续建筑",
    "lengthOfSchooling": "全日制18个月/非全日制36个月",
    "fee": "135000元"
}, {
    "location": "江苏",
    "name": "西交利物浦大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "可持续能源技术",
    "lengthOfSchooling": "全日制18个月",
    "fee": "180000元"
}, {
    "location": "江苏",
    "name": "西交利物浦大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "媒体与传播",
    "lengthOfSchooling": "全日制18个月",
    "fee": "150000元"
}, {
    "location": "江苏",
    "name": "西交利物浦大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "模式识别与智能系统",
    "lengthOfSchooling": "全日制18个月",
    "fee": "180000元"
}, {
    "location": "江苏",
    "name": "西交利物浦大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "中国研究",
    "lengthOfSchooling": "全日制18个月",
    "fee": "180000元"
}, {
    "location": "江苏",
    "name": "西交利物浦大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "人机交互",
    "lengthOfSchooling": "全日制18个月",
    "fee": "180000元"
}, {
    "location": "江苏",
    "name": "西交利物浦大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "商业分析",
    "lengthOfSchooling": "全日制18个月",
    "fee": "180000元"
}, {
    "location": "江苏",
    "name": "西交利物浦大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "社会网络计算技术",
    "lengthOfSchooling": "全日制18个月",
    "fee": "180000元"
}, {
    "location": "江苏",
    "name": "西交利物浦大学",
    "type": [SchoolType.FULL_TIME, SchoolType.PART_TIME],
    "majorName": "数字化教育",
    "lengthOfSchooling": "全日制24个月/非全日制36个月",
    "fee": "200000元"
}, {
    "location": "江苏",
    "name": "西交利物浦大学",
    "type": [SchoolType.FULL_TIME, SchoolType.PART_TIME],
    "majorName": "土木工程",
    "lengthOfSchooling": "全日制18个月/非全日制36个月",
    "fee": "135000元"
}, {
    "location": "江苏",
    "name": "西交利物浦大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "投资管理",
    "lengthOfSchooling": "全日制18个月",
    "fee": "180000元"
}, {
    "location": "江苏",
    "name": "西交利物浦大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "文化创意产业",
    "lengthOfSchooling": "全日制24个月",
    "fee": "200000元"
}, {
    "location": "江苏",
    "name": "西交利物浦大学",
    "type": [SchoolType.FULL_TIME, SchoolType.PART_TIME],
    "majorName": "项目管理",
    "lengthOfSchooling": "全日制18个月/非全日制30个月",
    "fee": "180000元"
}, {
    "location": "江苏",
    "name": "西交利物浦大学",
    "type": [SchoolType.FULL_TIME, SchoolType.PART_TIME],
    "majorName": "药学",
    "lengthOfSchooling": "全日制24个月/非全日制36个月",
    "fee": "176000元"
}, {
    "location": "江苏",
    "name": "西交利物浦大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "应用信息学",
    "lengthOfSchooling": "全日制18个月",
    "fee": "180000元"
}, {
    "location": "江苏",
    "name": "西交利物浦大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "应用统计学",
    "lengthOfSchooling": "全日制18个月",
    "fee": "132000元"
}, {
    "location": "江苏",
    "name": "西交利物浦大学",
    "type": [SchoolType.FULL_TIME, SchoolType.PART_TIME],
    "majorName": "药物化学",
    "lengthOfSchooling": "全日制24个月/非全日制36个月",
    "fee": "176000元"
}, {
    "location": "江苏",
    "name": "西交利物浦大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "应用语言学",
    "lengthOfSchooling": "全日制18个月",
    "fee": "150000元"
}, {
    "location": "江苏",
    "name": "西交利物浦大学",
    "type": [SchoolType.FULL_TIME, SchoolType.PART_TIME],
    "majorName": "运营与供应链管理",
    "lengthOfSchooling": "全日制18个月/非全日制36个月",
    "fee": "180000元"
}, {
    "location": "江苏",
    "name": "西交利物浦大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "专业会计",
    "lengthOfSchooling": "全日制18个月",
    "fee": "180000元"
}, {
    "location": "江苏",
    "name": "西交利物浦大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "材料科学与工程",
    "lengthOfSchooling": "全日制24个月",
    "fee": "180000元"
}, {
    "location": "江苏",
    "name": "西交利物浦大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "城市规划",
    "lengthOfSchooling": "全日制18个月",
    "fee": "135000元"
}, {
    "location": "江苏",
    "name": "西交利物浦大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "城市规划",
    "lengthOfSchooling": "全日制18个月",
    "fee": "135000元"
}, {
    "location": "江苏",
    "name": "西交利物浦大学",
    "type": [SchoolType.FULL_TIME, SchoolType.PART_TIME],
    "majorName": "创业与创新",
    "lengthOfSchooling": "全日制24个月/非全日制42个月",
    "fee": "200000元"
}, {
    "location": "江苏",
    "name": "西交利物浦大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "低碳电力与能源技术",
    "lengthOfSchooling": "全日制18个月",
    "fee": "180000元"
}, {
    "location": "江苏",
    "name": "西交利物浦大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "多媒体通信",
    "lengthOfSchooling": "全日制18个月",
    "fee": "180000元"
}, {
    "location": "江苏",
    "name": "西交利物浦大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "对外英语教育",
    "lengthOfSchooling": "全日制18个月",
    "fee": "150000元"
}, {
    "location": "江苏",
    "name": "西交利物浦大学",
    "type": [SchoolType.FULL_TIME, SchoolType.PART_TIME],
    "majorName": "儿童发展与家庭教育学",
    "lengthOfSchooling": "全日制18个月/非全日制30个月",
    "fee": "150000元"
}, {
    "location": "江苏",
    "name": "西交利物浦大学",
    "type": [SchoolType.FULL_TIME, SchoolType.PART_TIME],
    "majorName": "分子生物学",
    "lengthOfSchooling": "全日制24个月/非全日制36个月",
    "fee": "180000元"
}, {
    "location": "江苏",
    "name": "西交利物浦大学",
    "type": [SchoolType.FULL_TIME, SchoolType.PART_TIME],
    "majorName": "国际关系",
    "lengthOfSchooling": "全日制24个月/非全日制36个月",
    "fee": "150000元"
}, {
    "location": "江苏",
    "name": "西交利物浦大学",
    "type": [SchoolType.FULL_TIME, SchoolType.PART_TIME],
    "majorName": "国际化教育",
    "lengthOfSchooling": "全日制18个月/非全日制36个月",
    "fee": "150000元"
}, {
    "location": "江苏",
    "name": "西交利物浦大学",
    "type": [SchoolType.FULL_TIME, SchoolType.PART_TIME],
    "majorName": "国际商务与全球事务",
    "lengthOfSchooling": "全日制18个月/非全日制36个月",
    "fee": "180000元"
}, {
    "location": "江苏",
    "name": "西交利物浦大学",
    "type": SchoolType.PART_TIME,
    "majorName": "国际工商管理硕士 (IMBA)",
    "lengthOfSchooling": "非全日制24个月",
    "fee": "320000元"
}, {
    "location": "江苏",
    "name": "西交利物浦大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "工业设计",
    "lengthOfSchooling": "全日制24个月",
    "fee": "180000元"
}, {
    "location": "浙江",
    "name": "宁波诺丁汉大学",
    "type": [SchoolType.FULL_TIME, SchoolType.ON_THE_JOB],
    "majorName": "城市化与可持续发展环境 ",
    "lengthOfSchooling": "全日制12个月/在职24个月",
    "fee": "100000（RMB）/学年"
}, {
    "location": "浙江",
    "name": "宁波诺丁汉大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "对外英语教学文",
    "lengthOfSchooling": "全日制12个月",
    "fee": "100000（RMB）/学年"
}, {
    "location": "浙江",
    "name": "宁波诺丁汉大学",
    "type": [SchoolType.FULL_TIME, SchoolType.ON_THE_JOB],
    "majorName": "国际关系与国际商务 ",
    "lengthOfSchooling": "全日制12个月/在职24-48个月",
    "fee": "100000（RMB）/学年"
}, {
    "location": "浙江",
    "name": "宁波诺丁汉大学",
    "type": [SchoolType.FULL_TIME, SchoolType.ON_THE_JOB],
    "majorName": "国际高等教育",
    "lengthOfSchooling": "全日制12个月/在职24-48个月",
    "fee": "100000（RMB）/学年"
}, {
    "location": "浙江",
    "name": "宁波诺丁汉大学",
    "type": [SchoolType.FULL_TIME, SchoolType.ON_THE_JOB],
    "majorName": "国际关系与世界历史学",
    "lengthOfSchooling": "全日制12个月/在职24-48个月",
    "fee": "100000（RMB）/学年"
}, {
    "location": "浙江",
    "name": "宁波诺丁汉大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "国际商务",
    "lengthOfSchooling": "全日制12个月",
    "fee": "100000（RMB）/学年"
}, {
    "location": "浙江",
    "name": "宁波诺丁汉大学",
    "type": [SchoolType.FULL_TIME, SchoolType.ON_THE_JOB],
    "majorName": "国际传播学",
    "lengthOfSchooling": "全日制12个月/在职24-48个月",
    "fee": "100000（RMB）/学年"
}, {
    "location": "浙江",
    "name": "宁波诺丁汉大学",
    "type": [SchoolType.FULL_TIME, SchoolType.ON_THE_JOB],
    "majorName": "金融和投资学",
    "lengthOfSchooling": "全日制12个月/在职24-48个月",
    "fee": "100000（RMB）/学年"
}, {
    "location": "浙江",
    "name": "宁波诺丁汉大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "应用语言学",
    "lengthOfSchooling": "全日制12个月",
    "fee": "100000（RMB）/学年"
}, {
    "location": "浙江",
    "name": "宁波诺丁汉大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "英语翻译",
    "lengthOfSchooling": "全日制12个月",
    "fee": "100000（RMB）/学年"
}, {
    "location": "浙江",
    "name": "宁波诺丁汉大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "国际管理",
    "lengthOfSchooling": "全日制12个月",
    "fee": "100000（RMB）/学年"
}, {
    "location": "浙江",
    "name": "宁波诺丁汉大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "国际管理",
    "lengthOfSchooling": "全日制12个月",
    "fee": "100000（RMB）/学年"
}, {
    "location": "浙江",
    "name": "宁波诺丁汉大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "国际管理",
    "lengthOfSchooling": "全日制12个月",
    "fee": "100000（RMB）/学年"
}, {
    "location": "浙江",
    "name": "宁波诺丁汉大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "创业与创新管理学",
    "lengthOfSchooling": "全日制12个月",
    "fee": "100000（RMB）/学年"
}, {
    "location": "浙江",
    "name": "宁波诺丁汉大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "国际商务",
    "lengthOfSchooling": "全日制12个月",
    "fee": "100000（RMB）/学年"
}, {
    "location": "浙江",
    "name": "宁波诺丁汉大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "金融和投资学",
    "lengthOfSchooling": "全日制24个月",
    "fee": "100000（RMB）/学年"
}, {
    "location": "浙江",
    "name": "宁波诺丁汉大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "金融和投资学理学硕士",
    "lengthOfSchooling": "全日制12个月",
    "fee": "100000（RMB）/学年"
}, {
    "location": "深圳",
    "name": "香港中文大学（深圳）",
    "type": SchoolType.FULL_TIME,
    "majorName": "同声传译",
    "lengthOfSchooling": "2年",
    "fee": "220000人民币"
}, {
    "location": "深圳",
    "name": "香港中文大学（深圳）",
    "type": SchoolType.FULL_TIME,
    "majorName": "翻译(笔译/口译)",
    "lengthOfSchooling": "1年",
    "fee": "100000人民币"
}, {
    "location": "深圳",
    "name": "香港中文大学（深圳）",
    "type": SchoolType.FULL_TIME,
    "majorName": "全球研究",
    "lengthOfSchooling": "1年",
    "fee": "120000人民币"
}, {
    "location": "深圳",
    "name": "香港中文大学（深圳）",
    "type": SchoolType.FULL_TIME,
    "majorName": "应用心理学",
    "lengthOfSchooling": "2年",
    "fee": "200000人民币"
}, {
    "location": "深圳",
    "name": "香港中文大学（深圳）",
    "type": SchoolType.FULL_TIME,
    "majorName": "城市学",
    "lengthOfSchooling": "1年",
    "fee": "140000人民币"
}, {
    "location": "深圳",
    "name": "香港中文大学（深圳）",
    "type": SchoolType.FULL_TIME,
    "majorName": "公共政策",
    "lengthOfSchooling": "1年",
    "fee": "180000人民币"
}, {
    "location": "深圳",
    "name": "香港中文大学（深圳）",
    "type": SchoolType.FULL_TIME,
    "majorName": "会计学",
    "lengthOfSchooling": "2年",
    "fee": "234000人民币"
}, {
    "location": "深圳",
    "name": "香港中文大学（深圳）",
    "type": SchoolType.FULL_TIME,
    "majorName": "经济学",
    "lengthOfSchooling": "2年",
    "fee": "216000人民币"
}, {
    "location": "深圳",
    "name": "香港中文大学（深圳）",
    "type": SchoolType.FULL_TIME,
    "majorName": "金融学",
    "lengthOfSchooling": "1.5年",
    "fee": "268000人民币"
}, {
    "location": "深圳",
    "name": "香港中文大学（深圳）",
    "type": SchoolType.FULL_TIME,
    "majorName": "管理学",
    "lengthOfSchooling": "2年",
    "fee": "358000人民币"
}, {
    "location": "深圳",
    "name": "香港中文大学（深圳）",
    "type": SchoolType.FULL_TIME,
    "majorName": "数据科学",
    "lengthOfSchooling": "2年",
    "fee": "228000人民币"
}, {
    "location": "深圳",
    "name": "香港中文大学（深圳）",
    "type": SchoolType.FULL_TIME,
    "majorName": "供应链与物流管理",
    "lengthOfSchooling": "2年",
    "fee": "360000人民币"
}, {
    "location": "深圳",
    "name": "香港中文大学（深圳）",
    "type": SchoolType.FULL_TIME,
    "majorName": "通信工程",
    "lengthOfSchooling": "2年",
    "fee": "252000人民币"
}, {
    "location": "深圳",
    "name": "香港中文大学（深圳）",
    "type": SchoolType.FULL_TIME,
    "majorName": "金融工程",
    "lengthOfSchooling": "2年",
    "fee": "220000人民币"
}, {
    "location": "深圳",
    "name": "香港中文大学（深圳）",
    "type": SchoolType.FULL_TIME,
    "majorName": "市场营销学",
    "lengthOfSchooling": "1.5年",
    "fee": "228000人民币"
}, {
    "location": "深圳",
    "name": "香港中文大学（深圳）",
    "type": SchoolType.FULL_TIME,
    "majorName": "信息管理与商业分析",
    "lengthOfSchooling": "2年",
    "fee": "252000人民币"
}, {
    "location": "深圳",
    "name": "香港中文大学（深圳）",
    "type": SchoolType.FULL_TIME,
    "majorName": "生物信息学",
    "lengthOfSchooling": "1.5年",
    "fee": "175000人民币"
}, {
    "location": "深圳",
    "name": "香港中文大学（深圳）",
    "type": SchoolType.FULL_TIME,
    "majorName": "音乐表演",
    "lengthOfSchooling": "2年",
    "fee": "120000人民币"
}, {
    "location": "浙江",
    "name": "温州肯恩大学",
    "type": [SchoolType.FULL_TIME, SchoolType.PART_TIME],
    "majorName": "教育领导学博士(全日制/非)",
    "lengthOfSchooling": "3.5-6年\n",
    "fee": "25-45万\n"
}, {
    "location": "浙江",
    "name": "温州肯恩大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "生物技术科学(全日制)",
    "lengthOfSchooling": "2年",
    "fee": "11万"
}, {
    "location": "浙江",
    "name": "温州肯恩大学",
    "type": [SchoolType.FULL_TIME, SchoolType.PART_TIME],
    "majorName": "国际英语教学(全日制/非)",
    "lengthOfSchooling": "1.5-2年",
    "fee": "11万"
}, {
    "location": "浙江",
    "name": "温州肯恩大学",
    "type": [SchoolType.FULL_TIME, SchoolType.PART_TIME],
    "majorName": "建筑学(全日制/非)",
    "lengthOfSchooling": "2-3年",
    "fee": "16万"
}, {
    "location": "浙江",
    "name": "温州肯恩大学",
    "type": SchoolType.FULL_TIME,
    "majorName": "计算机信息系统(全日制)",
    "lengthOfSchooling": "1.5年",
    "fee": "11万"
}, {
    "location": "浙江",
    "name": "温州肯恩大学",
    "type": [SchoolType.FULL_TIME, SchoolType.PART_TIME],
    "majorName": "国际工商管理(全日制/非)",
    "lengthOfSchooling": "2年",
    "fee": "18万"
}, {
    "location": "浙江",
    "name": "温州肯恩大学",
    "type": [SchoolType.FULL_TIME, SchoolType.PART_TIME],
    "majorName": "心理学(全日制/非)",
    "lengthOfSchooling": "2年",
    "fee": "11万"
}, {
    "location": "浙江",
    "name": "温州肯恩大学",
    "type": [SchoolType.FULL_TIME, SchoolType.PART_TIME],
    "majorName": "教育管理(全日制/非)",
    "lengthOfSchooling": "2年",
    "fee": "11万"
}]